# Generated by Django 4.0.4 on 2022-04-24 02:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogindexpage_blogarticlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='add additional text', required=True))]))], blank=True, null=True),
        ),
    ]
