# Generated by Django 4.0.4 on 2022-05-06 01:37

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_blogindexpage_blog_image_blogindexpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='blog_image',
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='add additional text', required=True))])), ('full_richtext', streams.blocks.RichTextBlock()), ('message', streams.blocks.MessageBlock())], blank=True, null=True),
        ),
    ]
